### ISSUE TITLE
rpi3 can not run discovery.py

### ISSUE THREAD

**Issue by zewenhs** [getsenic/gatt-python#12]
Hi  all, @larsblumberg  
when i run discovery.py which is in _example_ directory on my rpi3, it has same error shown as below, 
my python version is 3.4 and blueZ is 5.23
who can tell me how to solve this? thanks!

pi@raspberrypi:~/workspace/gatt-python/examples $ ./discovery1.py  
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/gatt/gatt_linux.py", line 137, in start_discovery
    self._adapter.SetDiscoveryFilter(discovery_filter)
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 70, in __call__
    return self._proxy_method(*args, **keywords)
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 145, in __call__
    **keywords)
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.UnknownMethod: Method "SetDiscoveryFilter" with signature "a{ss}" on interface "org.bluez.Adapter1" doesn't exist

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./discovery1.py", line 10, in <module>
    manager.start_discovery()
  File "/usr/local/lib/python3.4/dist-packages/gatt/gatt_linux.py", line 148, in start_discovery
    raise _error_from_dbus_error(e)
gatt.errors.Failed: Method "SetDiscoveryFilter" with signature "a{ss}" on interface "org.bluez.Adapter1" doesn't exist

![discovery1](https://user-images.githubusercontent.com/7780577/30200586-2920d8f6-94aa-11e7-9063-48282f2316a2.PNG)

**Comment by larsblumberg** [comment]
That is because you're using an old BlueZ library. Please follow the readme of this repository to install a recent version of BlueZ.

**Comment by tomster** [comment]
closing this now. @zewenhs if you still have any questions, please re-open, thanks!

**Comment by zewenhs** [comment]
Hi all: &&  @larsblumberg @tomster :
It's ok after update my BlueZ to 5.44. thank you!
I've got a question to consult  which is how to stop discovering(scannig) devices after I run _start_discovery_ process like in _discovering.py_?  I mean by coding(call some functions) not by CTRL+C.
What I want to accomplish is my pi3 can automatic discovery and connect a certain  ble device, how can i do this? thanks!

**Comment by larsblumberg** [comment]
Simply [call `stop_discovery()` on your `ControllerManager`](https://github.com/getsenic/gatt-python/blob/master/gatt/gatt_linux.py#L150) instance.

**Comment by zewenhs** [comment]
`manager = AnyDeviceManager(adapter_name='hci0')
\nmanager.start_discovery()
\nmanager.run()`

**Comment by zewenhs** [comment]
HI @larsblumberg 
But how to call `stop_discovery()`?  It seem it will go into a loop and block the code process after `start_discovery()` && `.run()`  shown as below
`manager = AnyDeviceManager(adapter_name='hci0')`
`manager.start_discovery()`
`manager.run()`

**Comment by larsblumberg** [comment]
Call `manager.stop_discovery()` when you discovered the BLE device you were looking for.

**Comment by zewenhs** [comment]
Hi @larsblumberg      
Like this， thank you for your help~
   if device is not None:
    +        if device.alias() == "小米语音遥控器":
    +           print("found telink rc")
    +           self.stop_discovery()
    +           self.stop()
            self.device_discovered(device)
