### ISSUE TITLE
writing a value to the client characteristics configuration descriptor

### ISSUE THREAD

**Issue by sitikanthaz** [getsenic/gatt-python#26]
I am writing an app to enable notification on glucose measurement characteristics but it will only work if I enable the CCCD. unable to write a value to that descriptor. plz help

**Comment by Snevzor** [comment]
On your Characteristic instance you can use .enable_notifications().

**Comment by sitikanthaz** [comment]
I am doing that but it's not receiving anything from the server i.e. glucometer. the characteristic_value_updated() is not showing any values. do I have to write anything to the descriptor handle 2902 to enable this notification?

**Comment by sitikanthaz** [comment]
Any info or example on this? how to write to a descriptor handle? when I try to write using write.value() it shows "operation not supported" error. and from the documentations of bluetooth glucose profile I found out that i have to pass '01' to this uuid 2902 which is a descriptor after which notifications will be enabled. Any development on this plz share.

**Comment by sitikanthaz** [comment]
I got it resolved now. the bluez program does enable the CCCD for notifications by default and you don't have to write anything to the CCCD handle anymore. I got confused by the old documentation of bluetooth profile. My bad :) . closing this
