### ISSUE TITLE
Does peripheral role supported? 

### ISSUE THREAD

**Issue by sherifshsffa91** [getsenic/gatt-python#43]
I need to ask if the gatt server (peripheral)  rule supported in this library

**Comment by ukBaz** [comment]
Yes, the peripheral role is support by the Bluezero library. Have you read the information in the documentation about how to configure your system for such a role?
https://bluezero.readthedocs.io/en/latest/system_setup.html#using-bluezero-for-a-peripheral-role-or-beacon

I think this ticket is a better place to discuss the code you raise in:
https://github.com/ukBaz/python-bluezero/issues/201#issuecomment-466211109

The UUID's you are using in your example are in the range that are reserved by the Bluetooth Special Interest Group (Bluetooth SIG) for officially adopted services and characteristics. That is, any value that fits with the base 128-bit UUID of
0000xxxx-0000-1000-8000-00805F9B34FB

The UUID's you are using seem familiar from the HM-10 module (ttp://www.martyncurrey.com/hm-10-bluetooth-4ble-modules/)
Which is providing UART style functionality over BLE. Is that what you are trying to do?

I have done an example with Nordic Semiconductor's custom UART Service using the same profile as implemented on the BBC micro:bit
https://lancaster-university.github.io/microbit-docs/resources/bluetooth/bluetooth_profile.html

My example for creating the UART peripheral in Bluezero is at:
https://bluezero.readthedocs.io/en/latest/examples.html#peripheral-nordic-uart-service

Maybe see if that example works on your system and then start modifying it for your own needs?
