### ISSUE TITLE
Cannot write_value twice through BlueZ

### ISSUE THREAD

**Issue by Slievenamon** [getsenic/gatt-python#46]
Hi, I'm using BlueZ 5.50, 
When I send value through BlueZ, it's work properly the first time but when I call the function a second time the dbus send me back an error (InProgress): 
write value failed
write value fail for characteristic  6e400002-b5a3-f393-e0a9-e50e24dcca9e , error,  In Progress
write value succeeded
write value succeeded for characteristic  6e400002-b5a3-f393-e0a9-e50e24dcca9e

my code :
        characteristic_tx.write_value(str)
        time.sleep(10)
        characteristic_tx.write_value(str)

Do I need to send something to clear BlueZ flag ?

I'm not used to Python, how can I generate interruption in GObject.MainLoop() to send data through BlueZ ?

**Comment by leontan111** [comment]
Hi Slievenamon,

really interested to know if this issue get solved?
