### ISSUE TITLE
gatt-python pendant to gatttools char-write-cmd

### ISSUE THREAD

**Issue by harbaum** [getsenic/gatt-python#9]
I am missing a way to send data to a device without the delay of receiving an answer like gatttool does with char-write-cmd. Does this exist?

**Comment by larsblumberg** [comment]
As far as I know from the developers of BlueZ – the underlying Linux Bluetooth stack being used by this module – that's currently not supported by BlueZ.

**Comment by harbaum** [comment]
Thanks. So it seems this old gatttool-wrapper-python stuff isn't so bad after all ...

**Comment by larsblumberg** [comment]
We were using it before and we found it quiet unstable/unreliable.
